[tool.poetry]
name = "wherobots-python-dbapi"
version = "0.1.0"
description = "Python DB-API driver for Wherobots DB"
authors = ["Maxime Petazzoni <max@wherobots.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{ include = "src" }]

[project.urls]
Homepage = "https://github.com/wherobots/wherobots-python-dbapi-driver"
Tracker = "https://github.com/wherobots/wherobots-python-dbapi-driver/issues"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
websockets = "^12.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^8.0.2"
black = "^24.2.0"
pre-commit = "^3.6.2"
conventional-pre-commit = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.format]
max-line-length = "88"

[tool.mypy]
strict = true
show_error_codes = true
